name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # גרסה מעודכנת

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.6.0  # גרסה מעודכנת

    - name: Deploy to EC2
      run: |
        ssh ec2-user@18.209.49.78 "cd /home/ec2-user/Nodejs-server-ran && git pull origin main && pm2 restart my-app && pm2 save"
